export const POVOLANI_PROFESE = [
    { id: 'administrátor', opt: ['ostatní pracovníci na úseku řízení a správy', 'provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'advokát', opt: ['pracovníci soudů, notářství, státních zastupitelství, advokacie'] },
    { id: 'agronom', opt: ['techničtí pracovníci'] },
    { id: 'analytik', opt: ['ostatní odborní pracovníci nevýrobní sféry', 'ostatní pracovníci na úseku řízení a správy',
                            'pracovníci na úseku financování, nákladů a tvorby cen', 'pracovníci na úseku informační soustavy',
                            'pracovníci na úseku peněžnictví, pojišťovnictví'] },
    { id: 'animátor', opt: ['pracovníci tisku, kultury a osvěty', 'pracovníci umění',
                            'provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'antropolog', opt: ['ostatní odborní pracovníci nevýrobní sféry', 'pedagogičtí pracovníci'] },
    { id: 'aranžér', opt: ['ostatní odborní pracovníci nevýrobní sféry'] },
    { id: 'archeolog', opt: ['ostatní odborní pracovníci nevýrobní sféry', 'pedagogičtí pracovníci'] },
    { id: 'architekt', opt: ['pedagogičtí pracovníci', 'pracovníci umění', 'techničtí pracovníci'] },
    { id: 'archivář', opt: ['pracovníci tisku, kultury a osvěty'] },
    { id: 'armovač', opt: ['stavební dělníci'] },
    { id: 'artista', opt: ['pracovníci umění'] },
    { id: 'asanátor', opt: ['ostatní odborní pracovníci nevýrobní sféry'] },
    { id: 'asfaltér', opt: ['stavební dělníci'] },
    { id: 'asistent', opt: ['administrativní pracovníci', 'ostatní ekonomičtí pracovníci', 'ostatní odborní pracovníci nevýrobní sféry',
            'ostatní pracovníci na úseku řízení a správy', 'ostatní zdravotničtí pracovníci', 'pedagogičtí pracovníci', 'pracovníci na úseku peněžnictví, pojišťovnictví',
         'pracovníci soudů, notářství, státních zastupitelství, advokacie', 'pracovníci státních správních orgánů', 'provozní pracovníci dopravy, obchodu, pošt a služeb', 'techničtí pracovníci', 'tvůrčí pracovníci vědy, výzkumu a vývoje'] },
    { id: 'astrolog', opt: ['tvůrčí pracovníci vědy, výzkumu a vývoje'] },
    { id: 'astronom', opt: ['tvůrčí pracovníci vědy, výzkumu a vývoje'] },
    { id: 'automechanik', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'bagrista', opt: ['stavební dělníci'] },
    { id: 'bachař', opt: ['pracovníci obranných a bezpečnostních orgánů'] },
    { id: 'baletka', opt: ['pracovníci umění'] },
    { id: 'balič', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb', 'skladoví pracovníci'] },
    { id: 'bankéř', opt: ['pracovníci na úseku peněžnictví, pojišťovnictví'] },
    { id: 'báňský úpravář', opt: ['dělníci při těžbě a úpravě surovin'] },
    { id: 'barvíř', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'baštýř', opt: ['ostatní pracovníci na úseku řízení a správy', 'zemědělští, lesní a rybářští pracovníci'] },
    { id: 'bednář', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'betonář', opt: ['stavební dělníci'] },
    { id: 'bezpečnostní technik', opt: ['ostatní odborní pracovníci nevýrobní sféry', 'techničtí pracovníci'] },
    { id: 'bibliograf', opt: ['pracovníci tisku, kultury a osvěty'] },
    { id: 'biochemik', opt: ['techničtí pracovníci', 'tvůrčí pracovníci vědy, výzkumu a vývoje'] },
    { id: 'botanik', opt: ['tvůrčí pracovníci vědy, výzkumu a vývoje'] },
    { id: 'brašnář', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'brusič', opt: ['dělníci při těžbě a úpravě surovin', 'zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'celní rada', opt: ['ostatní pracovníci na úseku řízení a správy', 'pracovníci státních správních orgánů', 'vedoucí pracovníci'] },
    { id: 'celník', opt: ['pracovníci státních správních orgánů'] },
    { id: 'celulózař', opt: ['dělníci při těžbě a úpravě surovin'] },
    { id: 'cestář', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb', 'zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'cihlář', opt: ['dělníci při těžbě a úpravě surovin'] },
    { id: 'cínař', opt: ['dělníci při těžbě a úpravě surovin'] },
    { id: 'cukrář', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'cukrovarník', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'cvičitel tělocviku', opt: ['sportovní a tělovýchovní pracovníci'] },
    { id: 'cvičitel zvířat', opt: ['ostatní odborní pracovníci nevýrobní sféry'] },
    { id: 'čalouník', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'čerpadlář beznínové pumpy', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'číšník', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'dealer', opt: ['odborní pracovníci na úseku obchodních činností', 'provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'dekoratér', opt: ['ostatní odborní pracovníci nevýrobní sféry', 'pracovníci umění'] },
    { id: 'dělník domácí', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'dělník manipulační', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb', 'skladoví pracovníci'] },
    { id: 'dělník na pile', opt: ['dělníci při těžbě a úpravě surovin'] },
    { id: 'dělník na stavbě', opt: ['stavební dělníci'] },
    { id: 'dělník pomocný', opt: ['dělníci při těžbě a úpravě surovin', 'provozní pracovníci dopravy, obchodu, pošt a služeb', 'skladoví pracovníci', 'stavební dělníci', 'zemědělští, lesní a rybářští pracovníci', 'zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'dělník při těžbě surovin', opt: ['dělníci při těžbě a úpravě surovin'] },
    { id: 'dělník při úpravě surovin', opt: ['dělníci při těžbě a úpravě surovin'] },
    { id: 'dělník v lesnictví', opt: ['zemědělští, lesní a rybářští pracovníci'] },
    { id: 'dělník v rybářství', opt: ['zemědělští, lesní a rybářští pracovníci'] },
    { id: 'dělník v zemědělství', opt: ['zemědělští, lesní a rybářští pracovníci'] },
    { id: 'deratizátor', opt: ['ostatní odborní pracovníci nevýrobní sféry'] },
    { id: 'deštníkář', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'detektiv', opt: ['ostatní odborní pracovníci nevýrobní sféry', 'pracovníci obranných a bezpečnostních orgánů'] },
    { id: 'dialogista', opt: ['ostatní odborní pracovníci nevýrobní sféry', 'pracovníci tisku, kultury a osvěty'] },
    { id: 'dílenský plánovač', opt: ['ostatní odborní pracovníci nevýrobní sféry', 'ostatní pracovníci na úseku řízení a správy'] },
    { id: 'diplomat', opt: ['ostatní ekonomičtí pracovníci', 'ostatní odborní pracovníci nevýrobní sféry'] },
    { id: 'dirigent', opt: ['pracovníci umění'] },
    { id: 'dispečer', opt: ['ostatní pracovníci na úseku řízení a správy', 'pracovníci na úseku informační soustavy', 'provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'disponent', opt: ['pracovníci na úseku peněžnictví, pojišťovnictví', 'provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'dlaždič', opt: ['stavební dělníci'] },
    { id: 'domovník', opt: ['ostatní odborní pracovníci nevýrobní sféry'] },
    { id: 'doručovatel poštovní', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'dozorce', opt: ['pracovníci obranných a bezpečnostních orgánů'] },
    { id: 'dozorčí', opt: ['ostatní pracovníci na úseku řízení a správy', 'provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'dramaturg', opt: ['pracovníci tisku, kultury a osvěty', 'pracovníci umění'] },
    { id: 'dražebník', opt: ['ostatní odborní pracovníci nevýrobní sféry', 'pracovníci soudů, notářství, státních zastupitelství, advokacie'] },
    { id: 'dřevorubec', opt: ['dělníci při těžbě a úpravě surovin'] },
    { id: 'duchovní', opt: ['pracovníci církevních a náboženských společností'] },
    { id: 'ekolog', opt: ['ostatní odborní pracovníci nevýrobní sféry', 'pedagogičtí pracovníci', 'tvůrčí pracovníci vědy, výzkumu a vývoje'] },
    { id: 'ekonom', opt: ['ostatní ekonomičtí pracovníci', 'pedagogičtí pracovníci', 'tvůrčí pracovníci vědy, výzkumu a vývoje'] },
    { id: 'elektrikář', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'elektromechanik', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'elektromontér', opt: ['techničtí pracovníci', 'zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'elektrotechnik', opt: ['techničtí pracovníci'] },
    { id: 'energetik', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb', 'techničtí pracovníci'] },
    { id: 'epidemiolog', opt: ['lékař ostatní', 'ostatní zdravotničtí pracovníci', 'tvůrčí pracovníci vědy, výzkumu a vývoje'] },
    { id: 'expedient', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb', 'skladoví pracovníci'] },
    { id: 'fakturant', opt: ['pracovníci účetnictví, fakturace, kalkulace'] },
    { id: 'farář', opt: ['pracovníci církevních a náboženských společností'] },
    { id: 'farmaceut', opt: ['ostatní zdravotničtí pracovníci', 'tvůrčí pracovníci vědy, výzkumu a vývoje'] },
    { id: 'filozof', opt: ['pedagogičtí pracovníci', 'tvůrčí pracovníci vědy, výzkumu a vývoje'] },
    { id: 'finančník', opt: ['pracovníci na úseku peněžnictví, pojišťovnictví'] },
    { id: 'formovač (stavební kameniny)', opt: ['dělníci při těžbě a úpravě surovin', 'zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'fotograf', opt: ['ostatní odborní pracovníci nevýrobní sféry', 'pracovníci tisku, kultury a osvěty', 'pracovníci umění'] },
    { id: 'fotolaborant', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'fotomodelka', opt: ['pracovníci umění'] },
    { id: 'fotoreportér', opt: ['pracovníci tisku, kultury a osvěty'] },
    { id: 'foukač skla', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'frézař', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'fyzik', opt: ['techničtí pracovníci', 'tvůrčí pracovníci vědy, výzkumu a vývoje'] },
    { id: 'galvanizér', opt: ['dělníci při těžbě a úpravě surovin'] },
    { id: 'garderobier', opt: ['ostatní odborní pracovníci nevýrobní sféry', 'pracovníci tisku, kultury a osvěty'] },
    { id: 'gastronom', opt: ['ostatní odborní pracovníci nevýrobní sféry'] },
    { id: 'geodet', opt: ['ostatní odborní pracovníci nevýrobní sféry', 'tvůrčí pracovníci vědy, výzkumu a vývoje'] },
    { id: 'geofyzik', opt: ['techničtí pracovníci', 'tvůrčí pracovníci vědy, výzkumu a vývoje'] },
    { id: 'geolog', opt: ['ostatní odborní pracovníci nevýrobní sféry'] },
    { id: 'geomechanik', opt: ['dělníci při těžbě a úpravě surovin', 'techničtí pracovníci'] },
    { id: 'grafik', opt: ['pracovníci tisku, kultury a osvěty', 'pracovníci umění', 'techničtí pracovníci'] },
    { id: 'gumař', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'hasič', opt: ['pracovníci požárních útvarů, podnikové ostrahy'] },
    { id: 'herec', opt: ['pracovníci tisku, kultury a osvěty', 'pracovníci umění'] },
    { id: 'hlasatel', opt: ['pracovníci tisku, kultury a osvěty'] },
    { id: 'hlídač', opt: ['pracovníci obranných a bezpečnostních orgánů', 'pracovníci požárních útvarů, podnikové ostrahy'] },
    { id: 'hodinář', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'holič', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'horník', opt: ['dělníci při těžbě a úpravě surovin'] },
    { id: 'horský průvodce', opt: ['ostatní odborní pracovníci nevýrobní sféry'] },
    { id: 'hospodyně', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'hosteska', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'hotelový zřízenec', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'houslař', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'hrázný', opt: ['ostatní odborní pracovníci nevýrobní sféry'] },
    { id: 'hrnčíř', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'hrobník', opt: ['ostatní odborní pracovníci nevýrobní sféry'] },
    { id: 'hudebník', opt: ['pracovníci tisku, kultury a osvěty', 'pracovníci umění'] },
    { id: 'hutník', opt: ['dělníci při těžbě a úpravě surovin'] },
    { id: 'hygienik', opt: ['ostatní zdravotničtí pracovníci'] },
    { id: 'chemik', opt: ['techničtí pracovníci', 'tvůrčí pracovníci vědy, výzkumu a vývoje'] },
    { id: 'choreograf', opt: ['pracovníci tisku, kultury a osvěty', 'pracovníci umění'] },
    { id: 'chovatel', opt: ['ostatní odborní pracovníci nevýrobní sféry'] },
    { id: 'iluzionista', opt: ['pracovníci tisku, kultury a osvěty', 'pracovníci umění'] },
    { id: 'inkasista', opt: ['pracovníci účetnictví, fakturace, kalkulace'] },
    { id: 'inspektor', opt: ['ostatní odborní pracovníci nevýrobní sféry', 'pedagogičtí pracovníci', 'pracovníci obranných a bezpečnostních orgánů', 'pracovníci požárních útvarů, podnikové ostrahy', 'provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'inspicient', opt: ['pracovníci umění'] },
    { id: 'instalatér', opt: ['stavební dělníci', 'zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'instruktor', opt: ['ostatní odborní pracovníci nevýrobní sféry', 'pracovníci obranných a bezpečnostních orgánů', 'sportovní a tělovýchovní pracovníci'] },
    { id: 'instrumentalista', opt: ['pracovníci umění'] },
    { id: 'instrumentář (zubní)', opt: ['ostatní zdravotničtí pracovníci'] },
    { id: 'izolatér', opt: ['stavební dělníci', 'zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'jeřábník', opt: ['řidiči ostatních vozidel', 'skladoví pracovníci'] },
    { id: 'jezný', opt: ['ostatní odborní pracovníci nevýrobní sféry'] },
    { id: 'jiné', opt: ['jiné'] },
    { id: 'kabelář', opt: ['stavební dělníci', 'zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'kadeřník', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'kalič', opt: ['dělníci při těžbě a úpravě surovin'] },
    { id: 'kalkulant', opt: ['pracovníci účetnictví, fakturace, kalkulace'] },
    { id: 'kameník', opt: ['pracovníci umění', 'zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'kameraman', opt: ['pracovníci tisku, kultury a osvěty', 'pracovníci umění'] },
    { id: 'kamnář', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'kapitán (loď, letadlo)', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'karosář', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'kartáčník', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'kartograf', opt: ['ostatní odborní pracovníci nevýrobní sféry'] },
    { id: 'kaskadér', opt: ['pracovníci tisku, kultury a osvěty', 'pracovníci umění'] },
    { id: 'keramik', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'klempíř', opt: ['stavební dělníci', 'zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'klíčník', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'kloboučník', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'knihař', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'knihovník', opt: ['pracovníci tisku, kultury a osvěty'] },
    { id: 'kočí', opt: ['řidiči ostatních vozidel'] },
    { id: 'koksař', opt: ['dělníci při těžbě a úpravě surovin'] },
    { id: 'komentátor', opt: ['pracovníci tisku, kultury a osvěty'] },
    { id: 'kominík', opt: ['ostatní odborní pracovníci nevýrobní sféry'] },
    { id: 'koncipient', opt: ['pracovníci soudů, notářství, státních zastupitelství, advokacie'] },
    { id: 'konferenciér', opt: ['pracovníci tisku, kultury a osvěty'] },
    { id: 'konstruktér', opt: ['techničtí pracovníci', 'tvůrčí pracovníci vědy, výzkumu a vývoje'] },
    { id: 'kontrolor', opt: ['ostatní odborní pracovníci nevýrobní sféry', 'ostatní pracovníci na úseku řízení a správy', 'provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'konzervář', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'konzervátor', opt: ['ostatní odborní pracovníci nevýrobní sféry'] },
    { id: 'kopáč', opt: ['stavební dělníci'] },
    { id: 'korektor', opt: ['ostatní odborní pracovníci nevýrobní sféry', 'pracovníci tisku, kultury a osvěty'] },
    { id: 'korepetitor', opt: ['pracovníci umění'] },
    { id: 'korkař', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'kosmetička', opt: ['ostatní zdravotničtí pracovníci'] },
    { id: 'kostelník', opt: ['pracovníci církevních a náboženských společností'] },
    { id: 'kostymér', opt: ['ostatní odborní pracovníci nevýrobní sféry', 'pracovníci tisku, kultury a osvěty'] },
    { id: 'košíkář', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'kotelník', opt: ['techničtí pracovníci'] },
    { id: 'kouzelník', opt: ['pracovníci tisku, kultury a osvěty', 'pracovníci umění'] },
    { id: 'kovář', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'kovoobráběč', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'kožešník', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'krajkářka', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'krejčí', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'kreslič', opt: ['ostatní odborní pracovníci nevýrobní sféry', 'pracovníci umění', 'techničtí pracovníci'] },
    { id: 'kriminalista', opt: ['pracovníci obranných a bezpečnostních orgánů'] },
    { id: 'krmič', opt: ['zemědělští, lesní a rybářští pracovníci'] },
    { id: 'krotitel', opt: ['ostatní odborní pracovníci nevýrobní sféry'] },
    { id: 'krupier', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'kuchař', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'kulisář', opt: ['pracovníci tisku, kultury a osvěty'] },
    { id: 'kurátor (správce sbírky)', opt: ['pracovníci tisku, kultury a osvěty', 'pracovníci umění'] },
    { id: 'kynolog', opt: ['ostatní odborní pracovníci nevýrobní sféry'] },
    { id: 'laborant', opt: ['ostatní odborní pracovníci nevýrobní sféry', 'ostatní zdravotničtí pracovníci', 'pedagogičtí pracovníci', 'techničtí pracovníci', 'veterináři'] },
    { id: 'lakýrník', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'lanovkář', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'lékárník', opt: ['ostatní odborní pracovníci nevýrobní sféry'] },
    { id: 'lékař', opt: ['lékař anesteziolog', 'lékař gynekolog-porodník', 'lékař chirurg', 'lékař ostatní'] },
    { id: 'lektor', opt: ['ostatní odborní pracovníci nevýrobní sféry', 'pedagogičtí pracovníci'] },
    { id: 'lepič', opt: ['stavební dělníci'] },
    { id: 'lepič plakátů', opt: ['pracovníci tisku, kultury a osvěty'] },
    { id: 'leptař', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'lesník', opt: ['techničtí pracovníci'] },
    { id: 'lešenář', opt: ['stavební dělníci'] },
    { id: 'letuška', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'likvidátor', opt: ['ostatní odborní pracovníci nevýrobní sféry', 'pracovníci na úseku peněžnictví, pojišťovnictví'] },
    { id: 'linař', opt: ['stavební dělníci'] },
    { id: 'listonoš', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'loutkař', opt: ['pracovníci umění', 'zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'malíř bytů', opt: ['stavební dělníci'] },
    { id: 'malíř porcelánu a skla', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'malíř umělecký', opt: ['pracovníci tisku, kultury a osvěty', 'pracovníci umění'] },
    { id: 'manažer', opt: ['ostatní odborní pracovníci nevýrobní sféry', 'ostatní pracovníci na úseku řízení a správy', 'vedoucí pracovníci'] },
    { id: 'manekýn', opt: ['pracovníci tisku, kultury a osvěty'] },
    { id: 'masér', opt: ['ostatní zdravotničtí pracovníci'] },
    { id: 'maskér', opt: ['pracovníci tisku, kultury a osvěty', 'pracovníci umění'] },
    { id: 'mechanik', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb', 'techničtí pracovníci', 'zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'měřič', opt: ['stavební dělníci', 'techničtí pracovníci'] },
    { id: 'metař', opt: ['stavební dělníci'] },
    { id: 'meteorolog', opt: ['ostatní odborní pracovníci nevýrobní sféry', 'tvůrčí pracovníci vědy, výzkumu a vývoje'] },
    { id: 'metodik', opt: ['ostatní odborní pracovníci nevýrobní sféry', 'ostatní pracovníci na úseku řízení a správy', 'pedagogičtí pracovníci'] },
    { id: 'mistr koncertní, zvuku, taneční', opt: ['pracovníci tisku, kultury a osvěty', 'pracovníci umění'] },
    { id: 'mistr odborný', opt: ['pedagogičtí pracovníci', 'techničtí pracovníci'] },
    { id: 'mlékař', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'mluvčí', opt: ['pracovníci tisku, kultury a osvěty'] },
    { id: 'mlynář', opt: ['techničtí pracovníci'] },
    { id: 'mnich', opt: ['pracovníci církevních a náboženských společností'] },
    { id: 'modelář', opt: ['techničtí pracovníci', 'zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'modelka', opt: ['pracovníci tisku, kultury a osvěty', 'pracovníci umění'] },
    { id: 'montér', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb', 'stavební dělníci', 'techničtí pracovníci', 'zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'mozaikář', opt: ['pracovníci umění', 'zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'muzikant', opt: ['pracovníci tisku, kultury a osvěty', 'pracovníci umění'] },
    { id: 'nakladatel', opt: ['pracovníci tisku, kultury a osvěty'] },
    { id: 'námořník', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'nástrojař', opt: ['techničtí pracovníci', 'zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'natěrač (lakýrník)', opt: ['stavební dělníci'] },
    { id: 'navigátor (letecký)', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'normovač', opt: ['techničtí pracovníci'] },
    { id: 'notář', opt: ['pracovníci soudů, notářství, státních zastupitelství, advokacie'] },
    { id: 'novinář', opt: ['pracovníci tisku, kultury a osvěty'] },
    { id: 'nožíř', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'obchodní zástupce', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'obchodník', opt: ['odborní pracovníci na úseku obchodních činností'] },
    { id: 'obkladač', opt: ['stavební dělníci'] },
    { id: 'obsluhovač výtahů', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'obuvník', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'opat', opt: ['pracovníci církevních a náboženských společností'] },
    { id: 'operátor', opt: ['pracovníci na úseku informační soustavy', 'techničtí pracovníci'] },
    { id: 'opravář', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'optik', opt: ['techničtí pracovníci', 'tvůrčí pracovníci vědy, výzkumu a vývoje'] },
    { id: 'osvětlovač', opt: ['pracovníci tisku, kultury a osvěty'] },
    { id: 'ošetřovatel lidí', opt: ['ostatní zdravotničtí pracovníci'] },
    { id: 'ošetřovatel skotu', opt: ['zemědělští, lesní a rybářští pracovníci'] },
    { id: 'ovocnář', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'památkář', opt: ['pracovníci tisku, kultury a osvěty', 'pracovníci umění'] },
    { id: 'papírník', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'parukář', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'pedikér (manikér)', opt: ['ostatní zdravotničtí pracovníci'] },
    { id: 'pekař', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'personalista', opt: ['ostatní odborní pracovníci nevýrobní sféry', 'ostatní pracovníci na úseku řízení a správy'] },
    { id: 'pěstitel zemědělských plodin', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'pilníkář', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'pilot', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'pivovarník', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'plavčík', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb', 'sportovní a tělovýchovní pracovníci'] },
    { id: 'pletař', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'plynař', opt: ['techničtí pracovníci'] },
    { id: 'podlahář', opt: ['stavební dělníci'] },
    { id: 'pokladní', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'pokojská', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'pokrývač', opt: ['stavební dělníci'] },
    { id: 'policista', opt: ['pracovníci obranných a bezpečnostních orgánů'] },
    { id: 'politik', opt: ['ostatní pracovníci na úseku řízení a správy'] },
    { id: 'popelář', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'porybný', opt: ['ostatní odborní pracovníci nevýrobní sféry', 'ostatní pracovníci na úseku řízení a správy'] },
    { id: 'posel (kurýr)', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'posunovač', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'potápěč', opt: ['ostatní odborní pracovníci nevýrobní sféry'] },
    { id: 'pracovník administrativy', opt: ['administrativní pracovníci'] },
    { id: 'pracovník advokacie', opt: ['pracovníci soudů, notářství, státních zastupitelství, advokacie'] },
    { id: 'pracovník bezpečnostních orgánů', opt: ['pracovníci obranných a bezpečnostních orgánů'] },
    { id: 'pracovník církevních společností', opt: ['pracovníci církevních a náboženských společností'] },
    { id: 'pracovník fakturace', opt: ['pracovníci účetnictví, fakturace, kalkulace'] },
    { id: 'pracovník kalkulace', opt: ['pracovníci účetnictví, fakturace, kalkulace'] },
    { id: 'pracovník kultury', opt: ['pracovníci tisku, kultury a osvěty'] },
    { id: 'pracovník na úseku financování', opt: ['pracovníci na úseku financování, nákladů a tvorby cen'] },
    { id: 'pracovník na úseku informační soustavy', opt: ['pracovníci na úseku informační soustavy'] },
    { id: 'pracovník na úseku nákladů', opt: ['pracovníci na úseku financování, nákladů a tvorby cen'] },
    { id: 'pracovník na úseku peněžnictví', opt: ['pracovníci na úseku peněžnictví, pojišťovnictví'] },
    { id: 'pracovník na úseku pojišťovnictví', opt: ['pracovníci na úseku peněžnictví, pojišťovnictví'] },
    { id: 'pracovník na úseku tvorby cen', opt: ['pracovníci na úseku financování, nákladů a tvorby cen'] },
    { id: 'pracovník náboženských společností', opt: ['pracovníci církevních a náboženských společností'] },
    { id: 'pracovník notářství', opt: ['pracovníci soudů, notářství, státních zastupitelství, advokacie'] },
    { id: 'pracovník obranných orgánů', opt: ['pracovníci obranných a bezpečnostních orgánů'] },
    { id: 'pracovník odborný na úseku obchodních činností', opt: ['odborní pracovníci na úseku obchodních činností'] },
    { id: 'pracovník odborný v nevýrobní sféře', opt: ['ostatní odborní pracovníci nevýrobní sféry'] },
    { id: 'pracovník ostatní ekonomický', opt: ['ostatní ekonomičtí pracovníci'] },
    { id: 'pracovník ostatní na úseku řízení a správy', opt: ['ostatní pracovníci na úseku řízení a správy'] },
    { id: 'pracovník ostatní ve zdravotnictví', opt: ['ostatní zdravotničtí pracovníci'] },
    { id: 'pracovník osvěty', opt: ['pracovníci tisku, kultury a osvěty'] },
    { id: 'pracovník pedagogický', opt: ['pedagogičtí pracovníci'] },
    { id: 'pracovník podnikové ostrahy', opt: ['pracovníci požárních útvarů, podnikové ostrahy'] },
    { id: 'pracovník požárních útvarů', opt: ['pracovníci požárních útvarů, podnikové ostrahy'] },
    { id: 'pracovník provozní na poště', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'pracovník provozní v dopravě', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'pracovník provozní v obchodě', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'pracovník provozní ve službách', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'pracovník sociální', opt: ['sociální pracovníci'] },
    { id: 'pracovník soudů', opt: ['pracovníci soudů, notářství, státních zastupitelství, advokacie'] },
    { id: 'pracovník státního zastupitelství', opt: ['pracovníci soudů, notářství, státních zastupitelství, advokacie'] },
    { id: 'pracovník státních správních orgánů', opt: ['pracovníci státních správních orgánů'] },
    { id: 'pracovník technický', opt: ['techničtí pracovníci'] },
    { id: 'pracovník tělovýchovy', opt: ['sportovní a tělovýchovní pracovníci'] },
    { id: 'pracovník tisku', opt: ['pracovníci tisku, kultury a osvěty'] },
    { id: 'pracovník tvůrčí ve vědě', opt: ['tvůrčí pracovníci vědy, výzkumu a vývoje'] },
    { id: 'pracovník tvůrčí ve vývoji', opt: ['tvůrčí pracovníci vědy, výzkumu a vývoje'] },
    { id: 'pracovník tvůrčí ve výzkumu', opt: ['tvůrčí pracovníci vědy, výzkumu a vývoje'] },
    { id: 'pracovník účetnictví', opt: ['pracovníci účetnictví, fakturace, kalkulace'] },
    { id: 'pracovník umění', opt: ['pracovníci umění'] },
    { id: 'pracovník v oblasti sportu', opt: ['sportovní a tělovýchovní pracovníci'] },
    { id: 'pracovník ve skladu', opt: ['skladoví pracovníci'] },
    { id: 'pracovník vedoucí', opt: ['vedoucí pracovníci'] },
    { id: 'pradlena', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'pranostik', opt: ['ostatní odborní pracovníci nevýrobní sféry', 'tvůrčí pracovníci vědy, výzkumu a vývoje'] },
    { id: 'právník', opt: ['ostatní odborní pracovníci nevýrobní sféry', 'ostatní pracovníci na úseku řízení a správy', 'pracovníci na úseku peněžnictví, pojišťovnictví', 'pracovníci soudů, notářství, státních zastupitelství, advokacie', 'pracovníci státních správních orgánů', 'vedoucí pracovníci'] },
    { id: 'pražič kávy', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'prodavač', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'producent', opt: ['pracovníci tisku, kultury a osvěty', 'pracovníci umění'] },
    { id: 'prognostik', opt: ['tvůrčí pracovníci vědy, výzkumu a vývoje'] },
    { id: 'programátor', opt: ['ostatní odborní pracovníci nevýrobní sféry', 'pracovníci na úseku informační soustavy'] },
    { id: 'projektant', opt: ['ostatní odborní pracovníci nevýrobní sféry'] },
    { id: 'průvodce', opt: ['pracovníci tisku, kultury a osvěty'] },
    { id: 'průvodčí', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'překladatel', opt: ['ostatní odborní pracovníci nevýrobní sféry', 'pracovníci tisku, kultury a osvěty'] },
    { id: 'převozník', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'psycholog', opt: ['lékař ostatní', 'tvůrčí pracovníci vědy, výzkumu a vývoje'] },
    { id: 'publicista', opt: ['pracovníci tisku, kultury a osvěty'] },
    { id: 'pyrotechnik', opt: ['ostatní odborní pracovníci nevýrobní sféry', 'pracovníci obranných a bezpečnostních orgánů'] },
    { id: 'rámař', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'recepční', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'redaktor', opt: ['pracovníci tisku, kultury a osvěty'] },
    { id: 'referent', opt: ['ostatní odborní pracovníci nevýrobní sféry'] },
    { id: 'rehabilitační pracovník', opt: ['ostatní zdravotničtí pracovníci'] },
    { id: 'rekvizitář', opt: ['pracovníci tisku, kultury a osvěty'] },
    { id: 'rentgenolog', opt: ['lékař ostatní', 'ostatní zdravotničtí pracovníci'] },
    { id: 'reportér', opt: ['pracovníci tisku, kultury a osvěty'] },
    { id: 'restaurátor', opt: ['pracovníci tisku, kultury a osvěty', 'pracovníci umění', 'zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'revírník', opt: ['ostatní odborní pracovníci nevýrobní sféry', 'ostatní pracovníci na úseku řízení a správy'] },
    { id: 'revizor', opt: ['ostatní odborní pracovníci nevýrobní sféry', 'ostatní pracovníci na úseku řízení a správy'] },
    { id: 'režisér', opt: ['pracovníci tisku, kultury a osvěty', 'pracovníci umění'] },
    { id: 'rolník', opt: ['zemědělští, lesní a rybářští pracovníci'] },
    { id: 'rukavičkář', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'rybář', opt: ['zemědělští, lesní a rybářští pracovníci'] },
    { id: 'rýsovač', opt: ['ostatní odborní pracovníci nevýrobní sféry', 'techničtí pracovníci'] },
    { id: 'rytec', opt: ['pracovníci umění', 'zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'ředitel', opt: ['vedoucí pracovníci'] },
    { id: 'řezač skla', opt: ['stavební dělníci'] },
    { id: 'řezbář', opt: ['pracovníci umění', 'zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'řezník (uzenář)', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'řidič (z povolání)', opt: ['řidiči nákladních automobilů', 'řídiči osobních automobilů', 'řidiči ostatních vozidel'] },
    { id: 'sanitář', opt: ['ostatní zdravotničtí pracovníci', 'řidiči ostatních vozidel'] },
    { id: 'sazeč', opt: ['dělníci při těžbě a úpravě surovin', 'pracovníci tisku, kultury a osvěty'] },
    { id: 'sbormistr', opt: ['pracovníci umění'] },
    { id: 'scénárista', opt: ['pracovníci tisku, kultury a osvěty', 'pracovníci umění'] },
    { id: 'securita bezpečnostní služba', opt: ['pracovníci obranných a bezpečnostních orgánů', 'pracovníci požárních útvarů, podnikové ostrahy'] },
    { id: 'sekretářka', opt: ['administrativní pracovníci'] },
    { id: 'servírka', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'seřizovač', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb', 'zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'skladatel', opt: ['pracovníci tisku, kultury a osvěty', 'pracovníci umění'] },
    { id: 'skladník', opt: ['skladoví pracovníci'] },
    { id: 'sklář', opt: ['dělníci při těžbě a úpravě surovin', 'pracovníci umění'] },
    { id: 'sklenář', opt: ['stavební dělníci', 'zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'sládek', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'slévač', opt: ['dělníci při těžbě a úpravě surovin'] },
    { id: 'smaltér', opt: ['dělníci při těžbě a úpravě surovin', 'zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'směnárník', opt: ['pracovníci na úseku peněžnictví, pojišťovnictví', 'provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'sociolog', opt: ['ostatní odborní pracovníci nevýrobní sféry', 'pedagogičtí pracovníci', 'tvůrčí pracovníci vědy, výzkumu a vývoje'] },
    { id: 'sochař', opt: ['pracovníci tisku, kultury a osvěty', 'pracovníci umění'] },
    { id: 'soudce', opt: ['pracovníci soudů, notářství, státních zastupitelství, advokacie'] },
    { id: 'soustružník', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'spisovatel', opt: ['pracovníci tisku, kultury a osvěty', 'pracovníci umění'] },
    { id: 'spojař', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb', 'techničtí pracovníci'] },
    { id: 'správce', opt: ['ostatní odborní pracovníci nevýrobní sféry', 'ostatní pracovníci na úseku řízení a správy', 'pracovníci tisku, kultury a osvěty', 'provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'starosta', opt: ['vedoucí pracovníci'] },
    { id: 'statik', opt: ['ostatní odborní pracovníci nevýrobní sféry', 'techničtí pracovníci', 'tvůrčí pracovníci vědy, výzkumu a vývoje'] },
    { id: 'státní zástupce', opt: ['pracovníci soudů, notářství, státních zastupitelství, advokacie'] },
    { id: 'stavbyvedoucí', opt: ['stavební dělníci'] },
    { id: 'stavěč dekorací', opt: ['pracovníci tisku, kultury a osvěty'] },
    { id: 'steward (na lodi)', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'strážník obecní policie', opt: ['pracovníci obranných a bezpečnostních orgánů'] },
    { id: 'strážný', opt: ['pracovníci obranných a bezpečnostních orgánů', 'pracovníci požárních útvarů, podnikové ostrahy'] },
    { id: 'strojník', opt: ['ostatní odborní pracovníci nevýrobní sféry', 'provozní pracovníci dopravy, obchodu, pošt a služeb', 'techničtí pracovníci'] },
    { id: 'strojvedoucí', opt: ['řidiči ostatních vozidel'] },
    { id: 'střelmistr', opt: ['stavební dělníci', 'techničtí pracovníci'] },
    { id: 'střihač filmu', opt: ['pracovníci tisku, kultury a osvěty', 'pracovníci umění'] },
    { id: 'studnař', opt: ['ostatní odborní pracovníci nevýrobní sféry'] },
    { id: 'svačinář', opt: ['ostatní odborní pracovníci nevýrobní sféry'] },
    { id: 'svářeč', opt: ['stavební dělníci', 'techničtí pracovníci'] },
    { id: 'šatnář', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'šéfkuchař', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'šička', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'školník', opt: ['ostatní odborní pracovníci nevýrobní sféry'] },
    { id: 'štukatér', opt: ['stavební dělníci'] },
    { id: 'švadlena', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'švec', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'tajemník', opt: ['administrativní pracovníci', 'ostatní odborní pracovníci nevýrobní sféry', 'ostatní pracovníci na úseku řízení a správy', 'pracovníci soudů, notářství, státních zastupitelství, advokacie', 'pracovníci státních správních orgánů', 'pracovníci tisku, kultury a osvěty', 'vedoucí pracovníci'] },
    { id: 'tanečník', opt: ['pracovníci tisku, kultury a osvěty', 'pracovníci umění'] },
    { id: 'tapetář', opt: ['stavební dělníci'] },
    { id: 'tavič', opt: ['dělníci při těžbě a úpravě surovin'] },
    { id: 'taxátor', opt: ['ostatní odborní pracovníci nevýrobní sféry', 'pracovníci na úseku peněžnictví, pojišťovnictví'] },
    { id: 'taxikář', opt: ['řidiči nákladních automobilů', 'řídiči osobních automobilů'] },
    { id: 'technik', opt: ['techničtí pracovníci', 'tvůrčí pracovníci vědy, výzkumu a vývoje'] },
    { id: 'technolog', opt: ['ostatní pracovníci na úseku řízení a správy', 'techničtí pracovníci', 'tvůrčí pracovníci vědy, výzkumu a vývoje'] },
    { id: 'telefonista', opt: ['pracovníci na úseku informační soustavy'] },
    { id: 'telegrafista', opt: ['pracovníci na úseku informační soustavy'] },
    { id: 'tesař', opt: ['stavební dělníci'] },
    { id: 'tiskař', opt: ['pracovníci tisku, kultury a osvěty', 'techničtí pracovníci'] },
    { id: 'tiskový mluvčí', opt: ['pracovníci tisku, kultury a osvěty'] },
    { id: 'tkadlec', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'tlumočník', opt: ['ostatní odborní pracovníci nevýrobní sféry', 'pracovníci tisku, kultury a osvěty'] },
    { id: 'topenář', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'topič', opt: ['techničtí pracovníci'] },
    { id: 'tovární jezdec', opt: ['řidiči nákladních automobilů', 'řídiči osobních automobilů', 'řidiči ostatních vozidel'] },
    { id: 'trenér sportu', opt: ['sportovní a tělovýchovní pracovníci'] },
    { id: 'truhlář', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'tunelář', opt: ['stavební dělníci'] },
    { id: 'účetní', opt: ['pracovníci účetnictví, fakturace, kalkulace'] },
    { id: 'učitel', opt: ['pedagogičtí pracovníci', 'sportovní a tělovýchovní pracovníci'] },
    { id: 'učitel v autoškole', opt: ['řidiči nákladních automobilů', 'řídiči osobních automobilů', 'řidiči ostatních vozidel'] },
    { id: 'údržbář', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'uhlíř', opt: ['dělníci při těžbě a úpravě surovin'] },
    { id: 'uklízečka', opt: ['ostatní odborní pracovníci nevýrobní sféry'] },
    { id: 'úředník', opt: ['ostatní odborní pracovníci nevýrobní sféry', 'ostatní pracovníci na úseku řízení a správy', 'pracovníci státních správních orgánů'] },
    { id: 'uvadeč', opt: ['pracovníci tisku, kultury a osvěty'] },
    { id: 'válcíř', opt: ['dělníci při těžbě a úpravě surovin'] },
    { id: 'vazač břemen', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb', 'skladoví pracovníci', 'stavební dělníci'] },
    { id: 'velitel', opt: ['pracovníci obranných a bezpečnostních orgánů', 'pracovníci požárních útvarů, podnikové ostrahy', 'provozní pracovníci dopravy, obchodu, pošt a služeb', 'vedoucí pracovníci'] },
    { id: 'veterinář', opt: ['veterináři'] },
    { id: 'vlakvedoucí', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'vlásenkář', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'vodohospodář', opt: ['ostatní odborní pracovníci nevýrobní sféry', 'ostatní pracovníci na úseku řízení a správy'] },
    { id: 'voják z povolání', opt: ['pracovníci obranných a bezpečnostních orgánů'] },
    { id: 'vrátný', opt: ['pracovníci požárních útvarů, podnikové ostrahy'] },
    { id: 'vrtač', opt: ['stavební dělníci'] },
    { id: 'výbušninář', opt: ['pracovníci obranných a bezpečnostních orgánů', 'stavební dělníci'] },
    { id: 'vyhazovač', opt: ['pracovníci požárních útvarů, podnikové ostrahy'] },
    { id: 'výhybkář', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'vychovatel', opt: ['pedagogičtí pracovníci'] },
    { id: 'vykonavatel', opt: ['pracovníci soudů, notářství, státních zastupitelství, advokacie'] },
    { id: 'výpravčí', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'výrobce', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'vyšetřovatel', opt: ['pracovníci obranných a bezpečnostních orgánů', 'pracovníci požárních útvarů, podnikové ostrahy'] },
    { id: 'vyšívačka', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'výtvarník', opt: ['pracovníci tisku, kultury a osvěty', 'pracovníci umění'] },
    { id: 'výzkumník', opt: ['tvůrčí pracovníci vědy, výzkumu a vývoje'] },
    { id: 'zahradník', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'záchranář', opt: ['ostatní odborní pracovníci nevýrobní sféry'] },
    { id: 'zámečník', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'zásobovač', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb'] },
    { id: 'závozník', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb', 'skladoví pracovníci'] },
    { id: 'zdravotní sestra', opt: ['ostatní zdravotničtí pracovníci'] },
    { id: 'zedník', opt: ['stavební dělníci'] },
    { id: 'zemědělec', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'zeměměřič', opt: ['ostatní odborní pracovníci nevýrobní sféry'] },
    { id: 'zeměpisec', opt: ['tvůrčí pracovníci vědy, výzkumu a vývoje'] },
    { id: 'zlatník (klenotník)', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'zlatotepec', opt: ['pracovníci umění', 'zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'značkař', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb', 'zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'zootechnik', opt: ['techničtí pracovníci', 'veterináři'] },
    { id: 'zpěvák', opt: ['pracovníci tisku, kultury a osvěty', 'pracovníci umění'] },
    { id: 'zpracovatel', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'zpravodaj', opt: ['pracovníci tisku, kultury a osvěty'] },
    { id: 'zřízenec v nemocnici', opt: ['ostatní zdravotničtí pracovníci'] },
    { id: 'zvěrolékař', opt: ['veterináři'] },
    { id: 'zvonař', opt: ['zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'zvoník', opt: ['pracovníci církevních a náboženských společností'] },
    { id: 'zvukař', opt: ['pracovníci tisku, kultury a osvěty', 'pracovníci umění'] },
    { id: 'železář', opt: ['dělníci při těžbě a úpravě surovin', 'zpracovatelé (výrobci, opraváři, údržbáři)'] },
    { id: 'železničář', opt: ['provozní pracovníci dopravy, obchodu, pošt a služeb', 'techničtí pracovníci'] }
];

export const PROFESE = [
    { id: '1', 'label': 'administrativní pracovníci' },
    { id: '2', 'label': 'dělníci při těžbě a úpravě surovin' },
    { id: '3', 'label': 'lékař anesteziolog' },
    { id: '4', 'label': 'lékař gynekolog porodník' },
    { id: '5', 'label': 'lékař chirurg' },
    { id: '6', 'label': 'lékaři ostatní' },
    { id: '7', 'label': 'odborní pracovníci na úseku obchodních činností' },
    { id: '8', 'label': 'ostatní ekonomičtí pracovníci' },
    { id: '9', 'label': 'ostatní odborní pracovníci nevýrobní sféry' },
    { id: '10', 'label': 'ostatní pracovníci na úseku řízení a správy' },
    { id: '11', 'label': 'ostatní zdravotničtí pracovníci' },
    { id: '12', 'label': 'pedagogičtí pracovníci' },
    { id: '13', 'label': 'pracovníci církevních a náboženských společeností' },
    { id: '14', 'label': 'pracovníci na úseku financování, nákladů a tvorby cen' },
    { id: '15', 'label': 'pracovníci na úseku informační soustavy' },
    { id: '16', 'label': 'pracovníci na úseku peněžnictví, pojišťovnictví' },
    { id: '17', 'label': 'pracovníci obranných a bezpečnostních orgánů' },
    { id: '18', 'label': 'pracovníci požárních útvarů, podnikové ostrahy' },
    { id: '19', 'label': 'pracovníci soudů, notářství, státních zastupitelství, advokacie' },
    { id: '20', 'label': 'pracovníci státních správních orgánů' },
    { id: '21', 'label': 'pracovníci tisku, kultury a osvěty' },
    { id: '22', 'label': 'pracovníci účetnictví, fakturace, kalkulace' },
    { id: '23', 'label': 'pracovníci umění' },
    { id: '24', 'label': 'provozní pracovníci dopravy, obchodu, pošt a služeb' },
    { id: '25', 'label': 'řidiči nákladních automobilů' },
    { id: '26', 'label': 'řídiči osobních automobilů' },
    { id: '27', 'label': 'řidiči ostatních vozidel' },
    { id: '28', 'label': 'skladoví pracovníci' },
    { id: '29', 'label': 'sociální pracovníci' },
    { id: '30', 'label': 'sportovní a tělovýchovní pracovníci' },
    { id: '31', 'label': 'stavební dělníci' },
    { id: '32', 'label': 'techničtí pracovníci' },
    { id: '33', 'label': 'tvůrčí pracovníci vědy, výzkumu a vývoje' },
    { id: '34', 'label': 'vedoucí pracovníci' },
    { id: '35', 'label': 'veterináři' },
    { id: '36', 'label': 'zemědělští, lesní a rybářští pracovníci' },
    { id: '37', 'label': 'zpracovatelé (výrobci, opraváři, údržbáři)' },
    { id: '99', 'label': 'jiná' }
];

export const POVOLANI = [
	{ 'value': 'administrátor', 'label': 'administrátor' },
	{ 'value': 'advokát', 'label': 'advokát' },
	{ 'value': 'agronom', 'label': 'agronom' },
	{ 'value': 'analytik', 'label': 'analytik' },
	{ 'value': 'animátor', 'label': 'animátor' },
	{ 'value': 'antropolog', 'label': 'antropolog' },
	{ 'value': 'aranžér', 'label': 'aranžér' },
	{ 'value': 'archeolog', 'label': 'archeolog' },
	{ 'value': 'architekt', 'label': 'architekt' },
	{ 'value': 'archivář', 'label': 'archivář' },
	{ 'value': 'armovač', 'label': 'armovač' },
	{ 'value': 'artista', 'label': 'artista' },
	{ 'value': 'asanátor', 'label': 'asanátor' },
	{ 'value': 'asfaltér', 'label': 'asfaltér' },
	{ 'value': 'asistent', 'label': 'asistent' },
	{ 'value': 'astrolog', 'label': 'astrolog' },
	{ 'value': 'astronom', 'label': 'astronom' },
	{ 'value': 'automechanik', 'label': 'automechanik' },
	{ 'value': 'bagrista', 'label': 'bagrista' },
	{ 'value': 'bachař', 'label': 'bachař' },
	{ 'value': 'baletka', 'label': 'baletka' },
	{ 'value': 'balič', 'label': 'balič' },
	{ 'value': 'bankéř', 'label': 'bankéř' },
	{ 'value': 'báňský úpravář', 'label': 'báňský úpravář' },
	{ 'value': 'barvíř', 'label': 'barvíř' },
	{ 'value': 'baštýř', 'label': 'baštýř' },
	{ 'value': 'bednář', 'label': 'bednář' },
	{ 'value': 'betonář', 'label': 'betonář' },
	{ 'value': 'bezpečnostní technik', 'label': 'bezpečnostní technik' },
	{ 'value': 'bibliograf', 'label': 'bibliograf' },
	{ 'value': 'biochemik', 'label': 'biochemik' },
	{ 'value': 'botanik', 'label': 'botanik' },
	{ 'value': 'brašnář', 'label': 'brašnář' },
	{ 'value': 'brusič', 'label': 'brusič' },
	{ 'value': 'celní rada', 'label': 'celní rada' },
	{ 'value': 'celník', 'label': 'celník' },
	{ 'value': 'celulózař', 'label': 'celulózař' },
	{ 'value': 'cestář', 'label': 'cestář' },
	{ 'value': 'cihlář', 'label': 'cihlář' },
	{ 'value': 'cínař', 'label': 'cínař' },
	{ 'value': 'cukrář', 'label': 'cukrář' },
	{ 'value': 'cukrovarník', 'label': 'cukrovarník' },
	{ 'value': 'cvičitel tělocviku', 'label': 'cvičitel tělocviku' },
	{ 'value': 'cvičitel zvířat', 'label': 'cvičitel zvířat' },
	{ 'value': 'čalouník', 'label': 'čalouník' },
	{ 'value': 'čerpadlář beznínové pumpy', 'label': 'čerpadlář beznínové pumpy' },
	{ 'value': 'číšník', 'label': 'číšník' },
	{ 'value': 'dealer', 'label': 'dealer' },
	{ 'value': 'dekoratér', 'label': 'dekoratér' },
	{ 'value': 'dělník domácí', 'label': 'dělník domácí' },
	{ 'value': 'dělník na pile', 'label': 'dělník na pile' },
	{ 'value': 'dělník pomocný', 'label': 'dělník pomocný' },
	{ 'value': 'dělník při těžbě surovin', 'label': 'dělník při těžbě surovin' },
	{ 'value': 'dělník při úpravě surovin', 'label': 'dělník při úpravě surovin' },
	{ 'value': 'dělník na stavbě', 'label': 'dělník na stavbě' },
	{ 'value': 'dělník v lesnictví', 'label': 'dělník v lesnictví' },
	{ 'value': 'dělník v rybářství', 'label': 'dělník v rybářství' },
	{ 'value': 'dělník v zemědělství', 'label': 'dělník v zemědělství' },
	{ 'value': 'dělník manipulační', 'label': 'dělník manipulační' },
	{ 'value': 'deratizátor', 'label': 'deratizátor' },
	{ 'value': 'deštníkář', 'label': 'deštníkář' },
	{ 'value': 'detektiv', 'label': 'detektiv' },
	{ 'value': 'dialogista', 'label': 'dialogista' },
	{ 'value': 'dílenský plánovač', 'label': 'dílenský plánovač' },
	{ 'value': 'diplomat', 'label': 'diplomat' },
	{ 'value': 'dirigent', 'label': 'dirigent' },
	{ 'value': 'dispečer', 'label': 'dispečer' },
	{ 'value': 'disponent', 'label': 'disponent' },
	{ 'value': 'dlaždič', 'label': 'dlaždič' },
	{ 'value': 'domovník', 'label': 'domovník' },
	{ 'value': 'doručovatel poštovní', 'label': 'doručovatel poštovní' },
	{ 'value': 'dozorce', 'label': 'dozorce' },
	{ 'value': 'dozorčí', 'label': 'dozorčí' },
	{ 'value': 'dramaturg', 'label': 'dramaturg' },
	{ 'value': 'dražebník', 'label': 'dražebník' },
	{ 'value': 'dřevorubec', 'label': 'dřevorubec' },
	{ 'value': 'duchovní', 'label': 'duchovní' },
	{ 'value': 'ekolog', 'label': 'ekolog' },
	{ 'value': 'ekonom', 'label': 'ekonom' },
	{ 'value': 'elektrikář', 'label': 'elektrikář' },
	{ 'value': 'elektromechanik', 'label': 'elektromechanik' },
	{ 'value': 'elektromontér', 'label': 'elektromontér' },
	{ 'value': 'elektrotechnik', 'label': 'elektrotechnik' },
	{ 'value': 'energetik', 'label': 'energetik' },
	{ 'value': 'epidemiolog', 'label': 'epidemiolog' },
	{ 'value': 'expedient', 'label': 'expedient' },
	{ 'value': 'fakturant', 'label': 'fakturant' },
	{ 'value': 'farář', 'label': 'farář' },
	{ 'value': 'farmaceut', 'label': 'farmaceut' },
	{ 'value': 'filozof', 'label': 'filozof' },
	{ 'value': 'finančník', 'label': 'finančník' },
	{ 'value': 'formovač (stavební kameniny)', 'label': 'formovač (stavební kameniny)' },
	{ 'value': 'fotograf', 'label': 'fotograf' },
	{ 'value': 'fotolaborant', 'label': 'fotolaborant' },
	{ 'value': 'fotomodelka', 'label': 'fotomodelka' },
	{ 'value': 'fotoreportér', 'label': 'fotoreportér' },
	{ 'value': 'foukač skla', 'label': 'foukač skla' },
	{ 'value': 'frézař', 'label': 'frézař' },
	{ 'value': 'fyzik', 'label': 'fyzik' },
	{ 'value': 'galvanizér', 'label': 'galvanizér' },
	{ 'value': 'garderobier', 'label': 'garderobier' },
	{ 'value': 'gastronom', 'label': 'gastronom' },
	{ 'value': 'geodet', 'label': 'geodet' },
	{ 'value': 'geofyzik', 'label': 'geofyzik' },
	{ 'value': 'geolog', 'label': 'geolog' },
	{ 'value': 'geomechanik', 'label': 'geomechanik' },
	{ 'value': 'grafik', 'label': 'grafik' },
	{ 'value': 'gumař', 'label': 'gumař' },
	{ 'value': 'hasič', 'label': 'hasič' },
	{ 'value': 'herec', 'label': 'herec' },
	{ 'value': 'hlasatel', 'label': 'hlasatel' },
	{ 'value': 'hlídač', 'label': 'hlídač' },
	{ 'value': 'hodinář', 'label': 'hodinář' },
	{ 'value': 'holič', 'label': 'holič' },
	{ 'value': 'horník', 'label': 'horník' },
	{ 'value': 'horský průvodce', 'label': 'horský průvodce' },
	{ 'value': 'hospodyně', 'label': 'hospodyně' },
	{ 'value': 'hosteska', 'label': 'hosteska' },
	{ 'value': 'hotelový zřízenec', 'label': 'hotelový zřízenec' },
	{ 'value': 'houslař', 'label': 'houslař' },
	{ 'value': 'hrázný', 'label': 'hrázný' },
	{ 'value': 'hrnčíř', 'label': 'hrnčíř' },
	{ 'value': 'hrobník', 'label': 'hrobník' },
	{ 'value': 'hudebník', 'label': 'hudebník' },
	{ 'value': 'hutník', 'label': 'hutník' },
	{ 'value': 'hygienik', 'label': 'hygienik' },
	{ 'value': 'chemik', 'label': 'chemik' },
	{ 'value': 'choreograf', 'label': 'choreograf' },
	{ 'value': 'chovatel', 'label': 'chovatel' },
	{ 'value': 'iluzionista', 'label': 'iluzionista' },
	{ 'value': 'inkasista', 'label': 'inkasista' },
	{ 'value': 'inspektor', 'label': 'inspektor' },
	{ 'value': 'inspicient', 'label': 'inspicient' },
	{ 'value': 'instalatér', 'label': 'instalatér' },
	{ 'value': 'instruktor', 'label': 'instruktor' },
	{ 'value': 'instrumentalista', 'label': 'instrumentalista' },
	{ 'value': 'instrumentár (zubní)', 'label': 'instrumentár (zubní)' },
	{ 'value': 'izolatér', 'label': 'izolatér' },
	{ 'value': 'jeřábník', 'label': 'jeřábník' },
	{ 'value': 'jezný', 'label': 'jezný' },
	{ 'value': 'kabelář', 'label': 'kabelář' },
	{ 'value': 'kadeřník', 'label': 'kadeřník' },
	{ 'value': 'kalič', 'label': 'kalič' },
	{ 'value': 'kalkulant', 'label': 'kalkulant' },
	{ 'value': 'kameník', 'label': 'kameník' },
	{ 'value': 'kameraman', 'label': 'kameraman' },
	{ 'value': 'kamnář', 'label': 'kamnář' },
	{ 'value': 'kapitán (loď, letadlo)', 'label': 'kapitán (loď, letadlo)' },
	{ 'value': 'karosář', 'label': 'karosář' },
	{ 'value': 'kartáčník', 'label': 'kartáčník' },
	{ 'value': 'kartograf', 'label': 'kartograf' },
	{ 'value': 'kaskadér', 'label': 'kaskadér' },
	{ 'value': 'keramik', 'label': 'keramik' },
	{ 'value': 'klempíř', 'label': 'klempíř' },
	{ 'value': 'klíčník', 'label': 'klíčník' },
	{ 'value': 'kloboučník', 'label': 'kloboučník' },
	{ 'value': 'knihař', 'label': 'knihař' },
	{ 'value': 'knihovník', 'label': 'knihovník' },
	{ 'value': 'kočí', 'label': 'kočí' },
	{ 'value': 'koksař', 'label': 'koksař' },
	{ 'value': 'komentátor', 'label': 'komentátor' },
	{ 'value': 'kominík', 'label': 'kominík' },
	{ 'value': 'koncipient', 'label': 'koncipient' },
	{ 'value': 'konferenciér', 'label': 'konferenciér' },
	{ 'value': 'konstruktér', 'label': 'konstruktér' },
	{ 'value': 'kontrolor', 'label': 'kontrolor' },
	{ 'value': 'konzervář', 'label': 'konzervář' },
	{ 'value': 'konzervátor', 'label': 'konzervátor' },
	{ 'value': 'kopáč', 'label': 'kopáč' },
	{ 'value': 'korektor', 'label': 'korektor' },
	{ 'value': 'korepetitor', 'label': 'korepetitor' },
	{ 'value': 'korkař', 'label': 'korkař' },
	{ 'value': 'kosmetička', 'label': 'kosmetička' },
	{ 'value': 'kostelník', 'label': 'kostelník' },
	{ 'value': 'kostymér', 'label': 'kostymér' },
	{ 'value': 'košíkář', 'label': 'košíkář' },
	{ 'value': 'kotelník', 'label': 'kotelník' },
	{ 'value': 'kouzelník', 'label': 'kouzelník' },
	{ 'value': 'kovář', 'label': 'kovář' },
	{ 'value': 'kovoobráběč', 'label': 'kovoobráběč' },
	{ 'value': 'kožešník', 'label': 'kožešník' },
	{ 'value': 'krajkářka', 'label': 'krajkářka' },
	{ 'value': 'krejčí', 'label': 'krejčí' },
	{ 'value': 'kreslič', 'label': 'kreslič' },
	{ 'value': 'kriminalista', 'label': 'kriminalista' },
	{ 'value': 'krmič', 'label': 'krmič' },
	{ 'value': 'krotitel', 'label': 'krotitel' },
	{ 'value': 'krupier', 'label': 'krupier' },
	{ 'value': 'kuchař', 'label': 'kuchař' },
	{ 'value': 'kulisář', 'label': 'kulisář' },
	{ 'value': 'kurátor (správce sbírky)', 'label': 'kurátor (správce sbírky)' },
	{ 'value': 'kynolog', 'label': 'kynolog' },
	{ 'value': 'laborant', 'label': 'laborant' },
	{ 'value': 'lanovkář', 'label': 'lanovkář' },
	{ 'value': 'lakýrník', 'label': 'lakýrník' },
	{ 'value': 'lékárník', 'label': 'lékárník' },
	{ 'value': 'lékař', 'label': 'lékař' },
	{ 'value': 'lektor', 'label': 'lektor' },
	{ 'value': 'lepič', 'label': 'lepič' },
	{ 'value': 'lepič plakátu', 'label': 'lepič plakátu' },
	{ 'value': 'leptař', 'label': 'leptař' },
	{ 'value': 'lesník', 'label': 'lesník' },
	{ 'value': 'lešenář', 'label': 'lešenář' },
	{ 'value': 'letuška', 'label': 'letuška' },
	{ 'value': 'likvidátor', 'label': 'likvidátor' },
	{ 'value': 'linař', 'label': 'linař' },
	{ 'value': 'listonoš', 'label': 'listonoš' },
	{ 'value': 'loutkař', 'label': 'loutkař' },
	{ 'value': 'malíř bytu', 'label': 'malíř bytu' },
	{ 'value': 'malíř porcelánu a skla', 'label': 'malíř porcelánu a skla' },
	{ 'value': 'malíř umělecký', 'label': 'malíř umělecký' },
	{ 'value': 'manažer', 'label': 'manažer' },
	{ 'value': 'manekýn', 'label': 'manekýn' },
	{ 'value': 'masér', 'label': 'masér' },
	{ 'value': 'maskér', 'label': 'maskér' },
	{ 'value': 'mechanik', 'label': 'mechanik' },
	{ 'value': 'měrič', 'label': 'měrič' },
	{ 'value': 'metař', 'label': 'metař' },
	{ 'value': 'meteorolog', 'label': 'meteorolog' },
	{ 'value': 'metodik', 'label': 'metodik' },
	{ 'value': 'mistr odborný', 'label': 'mistr odborný' },
	{ 'value': 'mistr koncertní, zvuku, taneční', 'label': 'mistr koncertní, zvuku, taneční' },
	{ 'value': 'mlékař', 'label': 'mlékař' },
	{ 'value': 'mluvčí', 'label': 'mluvčí' },
	{ 'value': 'mlynář', 'label': 'mlynář' },
	{ 'value': 'mnich', 'label': 'mnich' },
	{ 'value': 'modelář', 'label': 'modelář' },
	{ 'value': 'modelka', 'label': 'modelka' },
	{ 'value': 'montér', 'label': 'montér' },
	{ 'value': 'mozaikář', 'label': 'mozaikář' },
	{ 'value': 'muzikant', 'label': 'muzikant' },
	{ 'value': 'nakladatel', 'label': 'nakladatel' },
	{ 'value': 'námořník', 'label': 'námořník' },
	{ 'value': 'nástrojař', 'label': 'nástrojař' },
	{ 'value': 'natirač (lakýrník)', 'label': 'natirač (lakýrník)' },
	{ 'value': 'navigátor (letecký)', 'label': 'navigátor (letecký)' },
	{ 'value': 'normovač', 'label': 'normovač' },
	{ 'value': 'notář', 'label': 'notář' },
	{ 'value': 'novinář', 'label': 'novinář' },
	{ 'value': 'nožíř', 'label': 'nožíř' },
	{ 'value': 'obchodní zástupce', 'label': 'obchodní zástupce' },
	{ 'value': 'obchodník', 'label': 'obchodník' },
	{ 'value': 'obkladač', 'label': 'obkladač' },
	{ 'value': 'obsluhovač výtahu', 'label': 'obsluhovač výtahu' },
	{ 'value': 'obuvník', 'label': 'obuvník' },
	{ 'value': 'opat', 'label': 'opat' },
	{ 'value': 'operátor', 'label': 'operátor' },
	{ 'value': 'opravář', 'label': 'opravář' },
	{ 'value': 'optik', 'label': 'optik' },
	{ 'value': 'osvětlovač', 'label': 'osvětlovač' },
	{ 'value': 'ošetřovatel lidí', 'label': 'ošetřovatel lidí' },
	{ 'value': 'ošetřovatel skotu', 'label': 'ošetřovatel skotu' },
	{ 'value': 'ovocnář', 'label': 'ovocnář' },
	{ 'value': 'památkář', 'label': 'památkář' },
	{ 'value': 'papírník', 'label': 'papírník' },
	{ 'value': 'parukář', 'label': 'parukář' },
	{ 'value': 'pedikér (manikér)', 'label': 'pedikér (manikér)' },
	{ 'value': 'pekař', 'label': 'pekař' },
	{ 'value': 'personalista', 'label': 'personalista' },
	{ 'value': 'pěstitel zemědělských plodin', 'label': 'pěstitel zemědělských plodin' },
	{ 'value': 'pilníkář', 'label': 'pilníkář' },
	{ 'value': 'pilot', 'label': 'pilot' },
	{ 'value': 'pivovarník', 'label': 'pivovarník' },
	{ 'value': 'plavčík', 'label': 'plavčík' },
	{ 'value': 'pletař', 'label': 'pletař' },
	{ 'value': 'plynař', 'label': 'plynař' },
	{ 'value': 'podlahář', 'label': 'podlahář' },
	{ 'value': 'pokladní', 'label': 'pokladní' },
	{ 'value': 'pokojská', 'label': 'pokojská' },
	{ 'value': 'pokrývač', 'label': 'pokrývač' },
	{ 'value': 'policista', 'label': 'policista' },
	{ 'value': 'politik', 'label': 'politik' },
	{ 'value': 'popelář', 'label': 'popelář' },
	{ 'value': 'porybný', 'label': 'porybný' },
	{ 'value': 'posel (kurýr)', 'label': 'posel (kurýr)' },
	{ 'value': 'posunovač', 'label': 'posunovač' },
	{ 'value': 'potápěč', 'label': 'potápěč' },
	{ 'value': 'pracovník administrativy', 'label': 'pracovník administrativy' },
	{ 'value': 'pracovník advokacie', 'label': 'pracovník advokacie' },
	{ 'value': 'pracovník bezpečnostních orgánu', 'label': 'pracovník bezpečnostních orgánu' },
	{ 'value': 'pracovník církevních společností', 'label': 'pracovník církevních společností' },
	{ 'value': 'pracovník fakturace', 'label': 'pracovník fakturace' },
	{ 'value': 'pracovník kalkulace', 'label': 'pracovník kalkulace' },
	{ 'value': 'pracovník kultury', 'label': 'pracovník kultury' },
	{ 'value': 'pracovník na úseku financování', 'label': 'pracovník na úseku financování' },
	{ 'value': 'pracovník na úseku informační soustavy', 'label': 'pracovník na úseku informační soustavy' },
	{ 'value': 'pracovník na úseku nákladů', 'label': 'pracovník na úseku nákladů' },
	{ 'value': 'pracovník na úseku penežnictví', 'label': 'pracovník na úseku penežnictví' },
	{ 'value': 'pracovník na úseku pojištovnictví', 'label': 'pracovník na úseku pojištovnictví' },
	{ 'value': 'pracovník na úseku tvorby cen', 'label': 'pracovník na úseku tvorby cen' },
	{ 'value': 'pracovník náboženských společností', 'label': 'pracovník náboženských společností' },
	{ 'value': 'pracovník notářství', 'label': 'pracovník notářství' },
	{ 'value': 'pracovník obranných orgánů', 'label': 'pracovník obranných orgánů' },
	{ 'value': 'pracovník odborný na úseku obchodních činností', 'label': 'pracovník odborný na úseku obchodních činností' },
	{ 'value': 'pracovník odborný v nevýrobní sféře', 'label': 'pracovník odborný v nevýrobní sfére' },
	{ 'value': 'pracovník ostatní ekonomický', 'label': 'pracovník ostatní ekonomický' },
	{ 'value': 'pracovník ostatní na úseku řízení a správy', 'label': 'pracovník ostatní na úseku řízení a správy' },
	{ 'value': 'pracovník ostatní ve zdravotnictví', 'label': 'pracovník ostatní ve zdravotnictví' },
	{ 'value': 'pracovník osvěty', 'label': 'pracovník osvěty' },
	{ 'value': 'pracovník pedagogický', 'label': 'pracovník pedagogický' },
	{ 'value': 'pracovník podnikové ostrahy', 'label': 'pracovník podnikové ostrahy' },
	{ 'value': 'pracovník požárních útvarů', 'label': 'pracovník požárních útvarů' },
	{ 'value': 'pracovník provozní na poště', 'label': 'pracovník provozní na poště' },
	{ 'value': 'pracovník provozní v dopravě', 'label': 'pracovník provozní v dopravě' },
	{ 'value': 'pracovník provozní v obchodě', 'label': 'pracovník provozní v obchodě' },
	{ 'value': 'pracovník provozní ve službách', 'label': 'pracovník provozní ve službách' },
	{ 'value': 'pracovník sociální', 'label': 'pracovník sociální' },
	{ 'value': 'pracovník soudu', 'label': 'pracovník soudu' },
	{ 'value': 'pracovník v oblasti sportu', 'label': 'pracovník v oblasti sportu' },
	{ 'value': 'pracovník státního zastupitelství', 'label': 'pracovník státního zastupitelství' },
	{ 'value': 'pracovník státních správních orgánu', 'label': 'pracovník státních správních orgánu' },
	{ 'value': 'pracovník technický', 'label': 'pracovník technický' },
	{ 'value': 'pracovník tělovýchovy', 'label': 'pracovník tělovýchovy' },
	{ 'value': 'pracovník tisku', 'label': 'pracovník tisku' },
	{ 'value': 'pracovník tvůrčí ve vědě', 'label': 'pracovník tvůrčí ve vědě' },
	{ 'value': 'pracovník tvůrčí ve vývoji', 'label': 'pracovník tvůrčí ve vývoji' },
	{ 'value': 'pracovník tvurčí ve výzkumu', 'label': 'pracovník tvurčí ve výzkumu' },
	{ 'value': 'pracovník účetnictví', 'label': 'pracovník účetnictví' },
	{ 'value': 'pracovník umění', 'label': 'pracovník umění' },
	{ 'value': 'pracovník ve skladu', 'label': 'pracovník ve skladu' },
	{ 'value': 'pracovník vedoucí', 'label': 'pracovník vedoucí' },
	{ 'value': 'pradlena', 'label': 'pradlena' },
	{ 'value': 'pranostik', 'label': 'pranostik' },
	{ 'value': 'právník', 'label': 'právník' },
	{ 'value': 'pražič kávy', 'label': 'pražič kávy' },
	{ 'value': 'prodavač', 'label': 'prodavač' },
	{ 'value': 'producent', 'label': 'producent' },
	{ 'value': 'prognostik', 'label': 'prognostik' },
	{ 'value': 'programátor', 'label': 'programátor' },
	{ 'value': 'projektant', 'label': 'projektant' },
	{ 'value': 'průvodce', 'label': 'průvodce' },
	{ 'value': 'průvodčí', 'label': 'průvodčí' },
	{ 'value': 'překladatel', 'label': 'překladatel' },
	{ 'value': 'převozník', 'label': 'převozník' },
	{ 'value': 'psycholog', 'label': 'psycholog' },
	{ 'value': 'publicista', 'label': 'publicista' },
	{ 'value': 'pyrotechnik', 'label': 'pyrotechnik' },
	{ 'value': 'rámař', 'label': 'rámař' },
	{ 'value': 'recepční', 'label': 'recepční' },
	{ 'value': 'redaktor', 'label': 'redaktor' },
	{ 'value': 'referent', 'label': 'referent' },
	{ 'value': 'rehabilitační pracovník', 'label': 'rehabilitační pracovník' },
	{ 'value': 'rekvizitář', 'label': 'rekvizitář' },
	{ 'value': 'rentgenolog', 'label': 'rentgenolog' },
	{ 'value': 'reportér', 'label': 'reportér' },
	{ 'value': 'restaurátor', 'label': 'restaurátor' },
	{ 'value': 'revírník', 'label': 'revírník' },
	{ 'value': 'revizor', 'label': 'revizor' },
	{ 'value': 'režisér', 'label': 'režisér' },
	{ 'value': 'rolník', 'label': 'rolník' },
	{ 'value': 'rukavičkár', 'label': 'rukavičkár' },
	{ 'value': 'rybář', 'label': 'rybář' },
	{ 'value': 'rýsovač', 'label': 'rýsovač' },
	{ 'value': 'rytec', 'label': 'rytec' },
	{ 'value': 'ředitel', 'label': 'ředitel' },
	{ 'value': 'řezač skla', 'label': 'řezač skla' },
	{ 'value': 'řezbář', 'label': 'řezbář' },
	{ 'value': 'řezník (uzenář)', 'label': 'řezník (uzenář)' },
	{ 'value': 'řidič (z povolání)', 'label': 'řidič (z povolání)' },
	{ 'value': 'sanitář', 'label': 'sanitář' },
	{ 'value': 'sazeč', 'label': 'sazeč' },
	{ 'value': 'sbormistr', 'label': 'sbormistr' },
	{ 'value': 'scénárista', 'label': 'scénárista' },
	{ 'value': 'securita bezpečnostní služba', 'label': 'securita bezpečnostní služba' },
	{ 'value': 'sekretářka', 'label': 'sekretářka' },
	{ 'value': 'servírka', 'label': 'servírka' },
	{ 'value': 'seřizovač', 'label': 'seřizovač' },
	{ 'value': 'skladatel', 'label': 'skladatel' },
	{ 'value': 'skladník', 'label': 'skladník' },
	{ 'value': 'sklář', 'label': 'sklář' },
	{ 'value': 'sklenář', 'label': 'sklenář' },
	{ 'value': 'sládek', 'label': 'sládek' },
	{ 'value': 'slévač', 'label': 'slévač' },
	{ 'value': 'smaltér', 'label': 'smaltér' },
	{ 'value': 'směnárník', 'label': 'směnárník' },
	{ 'value': 'sociolog', 'label': 'sociolog' },
	{ 'value': 'soudce', 'label': 'soudce' },
	{ 'value': 'sochař', 'label': 'sochař' },
	{ 'value': 'soustružník', 'label': 'soustružník' },
	{ 'value': 'spisovatel', 'label': 'spisovatel' },
	{ 'value': 'spojař', 'label': 'spojař' },
	{ 'value': 'správce', 'label': 'správce' },
	{ 'value': 'starosta', 'label': 'starosta' },
	{ 'value': 'statik', 'label': 'statik' },
	{ 'value': 'státní zástupce', 'label': 'státní zástupce' },
	{ 'value': 'stavbyvedoucí', 'label': 'stavbyvedoucí' },
	{ 'value': 'stavič dekorací', 'label': 'stavič dekorací' },
	{ 'value': 'steward (na lodi)', 'label': 'steward (na lodi)' },
	{ 'value': 'strážník obecní policie', 'label': 'strážník obecní policie' },
	{ 'value': 'strážný', 'label': 'strážný' },
	{ 'value': 'strojník', 'label': 'strojník' },
	{ 'value': 'strojvedoucí', 'label': 'strojvedoucí' },
	{ 'value': 'střelmistr', 'label': 'střelmistr' },
	{ 'value': 'střihač filmu', 'label': 'střihač filmu' },
	{ 'value': 'studnař', 'label': 'studnař' },
	{ 'value': 'svačinář', 'label': 'svačinář' },
	{ 'value': 'svářeč', 'label': 'svářeč' },
	{ 'value': 'šatnář', 'label': 'šatnář' },
	{ 'value': 'šéfkuchař', 'label': 'šéfkuchař' },
	{ 'value': 'šička', 'label': 'šička' },
	{ 'value': 'školník', 'label': 'školník' },
	{ 'value': 'štukatér', 'label': 'štukatér' },
	{ 'value': 'švadlena', 'label': 'švadlena' },
	{ 'value': 'švec', 'label': 'švec' },
	{ 'value': 'tajemník', 'label': 'tajemník' },
	{ 'value': 'tanečník', 'label': 'tanečník' },
	{ 'value': 'tapetář', 'label': 'tapetář' },
	{ 'value': 'tavič', 'label': 'tavič' },
	{ 'value': 'taxátor', 'label': 'taxátor' },
	{ 'value': 'taxikář', 'label': 'taxikář' },
	{ 'value': 'technik', 'label': 'technik' },
	{ 'value': 'technolog', 'label': 'technolog' },
	{ 'value': 'telefonista', 'label': 'telefonista' },
	{ 'value': 'telegrafista', 'label': 'telegrafista' },
	{ 'value': 'tesař', 'label': 'tesař' },
	{ 'value': 'tiskař', 'label': 'tiskař' },
	{ 'value': 'tiskový mluvčí', 'label': 'tiskový mluvčí' },
	{ 'value': 'tkadlec', 'label': 'tkadlec' },
	{ 'value': 'tlumočník', 'label': 'tlumočník' },
	{ 'value': 'topenář', 'label': 'topenář' },
	{ 'value': 'topič', 'label': 'topič' },
	{ 'value': 'tovární jezdec', 'label': 'tovární jezdec' },
	{ 'value': 'trenér sportu', 'label': 'trenér sportu' },
	{ 'value': 'truhlář', 'label': 'truhlář' },
	{ 'value': 'tunelář', 'label': 'tunelář' },
	{ 'value': 'účetní', 'label': 'účetní' },
	{ 'value': 'učitel', 'label': 'učitel' },
	{ 'value': 'učitel v autoškole', 'label': 'učitel v autoškole' },
	{ 'value': 'údržbář', 'label': 'údržbář' },
	{ 'value': 'uhlíř', 'label': 'uhlíř' },
	{ 'value': 'uklízečka', 'label': 'uklízečka' },
	{ 'value': 'úředník', 'label': 'úředník' },
	{ 'value': 'uvaděč', 'label': 'uvaděč' },
	{ 'value': 'válčíř', 'label': 'válčíř' },
	{ 'value': 'vazač břemen', 'label': 'vazač břemen' },
	{ 'value': 'velitel', 'label': 'velitel' },
	{ 'value': 'veterinář', 'label': 'veterinář' },
	{ 'value': 'vlakvedoucí', 'label': 'vlakvedoucí' },
	{ 'value': 'vlásenkář', 'label': 'vlásenkář' },
	{ 'value': 'vodohospodář', 'label': 'vodohospodář' },
	{ 'value': 'voják z povolání', 'label': 'voják z povolání' },
	{ 'value': 'vrátný', 'label': 'vrátný' },
	{ 'value': 'vrtař', 'label': 'vrtař' },
	{ 'value': 'výbušninář', 'label': 'výbušninář' },
	{ 'value': 'vyhazovač', 'label': 'vyhazovač' },
	{ 'value': 'výhybkář', 'label': 'výhybkář' },
	{ 'value': 'vychovatel', 'label': 'vychovatel' },
	{ 'value': 'vykonavatel', 'label': 'vykonavatel' },
	{ 'value': 'výpravčí', 'label': 'výpravčí' },
	{ 'value': 'výrobce', 'label': 'výrobce' },
	{ 'value': 'vyšetřovatel', 'label': 'vyšetřovatel' },
	{ 'value': 'vyšívařka', 'label': 'vyšívařka' },
	{ 'value': 'výtvarník', 'label': 'výtvarník' },
	{ 'value': 'výzkumník', 'label': 'výzkumník' },
	{ 'value': 'zahradník', 'label': 'zahradník' },
	{ 'value': 'záchranář', 'label': 'záchranář' },
	{ 'value': 'zámečník', 'label': 'zámečník' },
	{ 'value': 'zásobovač', 'label': 'zásobovač' },
	{ 'value': 'závozník', 'label': 'závozník' },
	{ 'value': 'zdravotní sestra', 'label': 'zdravotní sestra' },
	{ 'value': 'zedník', 'label': 'zedník' },
	{ 'value': 'zemědělec', 'label': 'zemědělec' },
	{ 'value': 'zeměměřič', 'label': 'zeměměřič' },
	{ 'value': 'zeměpisec', 'label': 'zeměpisec' },
	{ 'value': 'zlatník (klenotník)', 'label': 'zlatník (klenotník)' },
	{ 'value': 'zlatotepec', 'label': 'zlatotepec' },
	{ 'value': 'značkař', 'label': 'značkař' },
	{ 'value': 'zootechnik', 'label': 'zootechnik' },
	{ 'value': 'zpěvák', 'label': 'zpěvák' },
	{ 'value': 'zpracovatel', 'label': 'zpracovatel' },
	{ 'value': 'zpravodaj', 'label': 'zpravodaj' },
	{ 'value': 'zřízenec v nemocnici', 'label': 'zřízenec v nemocnici' },
	{ 'value': 'zvěrolékař', 'label': 'zvěrolékař' },
	{ 'value': 'zvonař', 'label': 'zvonař' },
	{ 'value': 'zvoník', 'label': 'zvoník' },
	{ 'value': 'zvukař', 'label': 'zvukař' },
	{ 'value': 'železář', 'label': 'železář' },
	{ 'value': 'železničář', 'label': 'železničář' },
	{ 'value': 'jiné', 'label': 'jiné' }
]
